version: '3'
vars:
  PLUGIN_NAME: devex-plugin-package-manager-emerge
tasks:
  build:
    desc: Build package-manager-emerge plugin for all platforms
    cmds:
      - mkdir -p dist\n      - GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version={{.VERSION | default \"dev\"}}" -o dist/devex-plugin-package-manager-emerge-linux-amd64 .\n      - GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X main.version={{.VERSION | default \"dev\"}}" -o dist/devex-plugin-package-manager-emerge-linux-arm64 .
  test:
    desc: Run tests
    cmds:
      - go test -v ./...
  lint:
    desc: Run linters
    cmds:
      - golangci-lint run
  install:local:
    desc: Install plugin locally for testing
    cmds:
      - task: build
      - mkdir -p ~/.devex/plugins
      - cp dist/\{{.PLUGIN_NAME}}-\{{OS}}-\{{ARCH}}* ~/.devex/plugins/\{{.PLUGIN_NAME}}
      - chmod +x ~/.devex/plugins/\{{.PLUGIN_NAME}}
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/
