version: 2

builds:
  - id: devex
    binary: devex
    main: ./cmd/devex
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - '6'
    mod_timestamp: '{{ .CommitTimestamp }}'

release:
  github:
    owner: jameswlane
    name: devex
  draft: true
  replace_existing_draft: true
  replace_existing_artifacts: true
  target_commitish: "{{ .Commit }}"
  discussion_category_name: General
  prerelease: auto
  make_latest: true
  mode: append
  header: |
    ## DevEx Release ({{ .Date }})
    Welcome to this new release!
  footer: |
    ## Thanks
    Those were the changes on {{ .Tag }}!
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"
  extra_files:
    - glob: ./assets/**/*
    - glob: ./config/**/*
    - glob: ./help/**/*
    - glob: ./README.md
  include_meta: true

snapshot:
  version_template: "{{.Version}}"

checksum:
  name_template: "devex_checksums.txt"