version: 2
project_name: devex
monorepo:
  tag_prefix: v
builds:
  - id: devex-cli
    main: ./apps/cli
    binary: devex
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"
      - "-X main.version={{.Version}}"
      - "-X main.commit={{.Commit}}"
      - "-X main.date={{.Date}}"
archives:
  - id: main-archive
    builds:
      - devex-cli
    name_template: devex_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: checksums.txt
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - ${signature}
      - "--detach-sign"
      - ${artifact}
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
  groups:
    - title: New Features
      regexp: ^.*?feat(\([[:word:]]+\))??!?:.+$
      order: 0
    - title: Bug Fixes
      regexp: ^.*?fix(\([[:word:]]+\))??!?:.+$
      order: 1
    - title: Plugin Updates
      regexp: ^.*?plugin(\([[:word:]]+\))??!?:.+$
      order: 2
    - title: Others
      order: 999
release:
  github:
    owner: jameswlane
    name: devex
  name_template: DevEx v{{ .Version }}
  mode: replace
  draft: false
  prerelease: auto
