site_name: DevEx Documentation
site_url: https://docs.devex.sh
repo_url: https://github.com/jameswlane/devex
theme:
    name: material
    palette:
        primary: blue
        accent: pink
    font:
        text: Roboto
        code: Roboto Mono
    favicon: img/favicon.ico

nav:
    - Home: index.md
    - CLI Reference:
          - Overview: cli/overview.md
          - Commands: cli/commands.md
    - Configuration:
          - Overview: configuration/overview.md
          - Apps: configuration/apps.md
          - Programming Languages: configuration/programming_languages.md
          - Databases: configuration/databases.md

plugins:
    - search
    - include-markdown
    - mermaid2
    - awesome-pages

markdown_extensions:
    - toc:
          permalink: true
    - tables
    - codehilite
    - admonition
