version: '3'
vars:
  PLUGIN_NAME: devex-plugin-desktop-mate
tasks:
  build:
    desc: Build MATE desktop plugin for all platforms
    cmds:
      - mkdir -p dist
      - GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version={{.VERSION | default "dev"}}" -o dist/{{.PLUGIN_NAME}}-linux-amd64 .
      - GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X main.version={{.VERSION | default "dev"}}" -o dist/{{.PLUGIN_NAME}}-linux-arm64 .
  test:
    desc: Run tests
    cmds:
      - go test -v ./...
  lint:
    desc: Run linters
    cmds:
      - golangci-lint run
  install:local:
    desc: Install plugin locally for testing
    cmds:
      - task: build
      - mkdir -p ~/.devex/plugins
      - cp dist/{{.PLUGIN_NAME}}-linux-{{ARCH}} ~/.devex/plugins/{{.PLUGIN_NAME}}
      - chmod +x ~/.devex/plugins/{{.PLUGIN_NAME}}
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/
