name: Proton VPN
description: VPN service by Proton
category: Optional Apps
desktop_environments:
  - gnome-family
linux:
  install_method: script
  install_command: 'wget https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.4_all.deb &&

    sudo dpkg -i ./protonvpn-stable-release_1.0.4_all.deb && sudo apt update &&

    sudo apt install proton-vpn-gnome-desktop libayatana-appindicator3-1 gir1.2-ayatanaappindicator3-0.1 gnome-shell-extension-appindicator

'
  uninstall_command: sudo apt remove proton-vpn-gnome-desktop libayatana-appindicator3-1 gir1.2-ayatanaappindicator3-0.1 gnome-shell-extension-appindicator
  dependencies:
    - apt
