name: Proton Pass
description: Password manager by Proton
category: Optional Apps
desktop_environments:
  - all
linux:
  install_method: deb
  install_command: wget https://proton.me/download/pass/linux/proton-pass_1.23.1_amd64.deb && sudo apt install ./proton-pass_1.23.1_amd64.deb
  uninstall_command: sudo apt remove proton-pass
  dependencies:
    - apt
