name: bat
description: A cat(1) clone with wings
category: Utilities
default: true
desktop_environments:
  - all
macos:
  install_method: brew
  install_command: bat
  uninstall_command: bat
  official_support: true
  alternatives:
    - install_method: macports
      install_command: bat
      uninstall_command: bat
      official_support: true
windows:
  install_method: winget
  install_command: sharkdp.bat
  uninstall_command: sharkdp.bat
  official_support: true
  alternatives:
    - install_method: chocolatey
      install_command: bat
      uninstall_command: bat
      official_support: true
    - install_method: scoop
      install_command: bat
      uninstall_command: bat
      official_support: true
linux:
  install_method: apt
  install_command: bat
  uninstall_command: bat
  official_support: true
  platform_requirements:
    - os: debian
    - os: ubuntu
  alternatives:
    - install_method: dnf
      install_command: bat
      uninstall_command: bat
      official_support: true
      platform_requirements:
        - os: fedora
        - os: centos
        - os: rhel
    - install_method: pacman
      install_command: bat
      uninstall_command: bat
      official_support: true
      platform_requirements:
        - os: arch
        - os: manjaro
    - install_method: zypper
      install_command: bat
      uninstall_command: bat
      official_support: true
      platform_requirements:
        - os: opensuse
    - install_method: emerge
      install_command: sys-apps/bat
      uninstall_command: sys-apps/bat
      official_support: true
      platform_requirements:
        - os: gentoo
    - install_method: eopkg
      install_command: bat
      uninstall_command: bat
      official_support: true
      platform_requirements:
        - os: solus
    - install_method: xbps
      install_command: bat
      uninstall_command: bat
      official_support: true
      platform_requirements:
        - os: void
    - install_method: apk
      install_command: bat
      uninstall_command: bat
      official_support: true
      platform_requirements:
        - os: alpine
    - install_method: nixpkgs
      install_command: bat
      uninstall_command: bat
      official_support: true
      platform_requirements:
        - os: nixos
    - install_method: snap
      install_command: bat
      uninstall_command: bat
      official_support: false
    - install_method: cargo
      install_command: bat
      uninstall_command: bat
      official_support: true
freebsd:
  install_method: pkg
  install_command: bat
  uninstall_command: bat
  official_support: true
openbsd:
  install_method: pkg_add
  install_command: bat
  uninstall_command: bat
  official_support: true
