name: fd-find
description: A simple, fast and user-friendly alternative to find
category: Utilities
default: true
desktop_environments:
  - all
macos:
  install_method: brew
  install_command: fd
  uninstall_command: fd
  official_support: true
  alternatives:
    - install_method: macports
      install_command: fd
      uninstall_command: fd
      official_support: true
windows:
  install_method: winget
  install_command: sharkdp.fd
  uninstall_command: sharkdp.fd
  official_support: true
  alternatives:
    - install_method: chocolatey
      install_command: fd
      uninstall_command: fd
      official_support: true
    - install_method: scoop
      install_command: fd
      uninstall_command: fd
      official_support: true
linux:
  install_method: apt
  install_command: fd-find
  uninstall_command: fd-find
  official_support: true
  platform_requirements:
    - os: debian
    - os: ubuntu
  post_install:
    - shell: mkdir -p $HOME/.local/bin
    - shell: ln -sf $(which fdfind) $HOME/.local/bin/fd
  alternatives:
    - install_method: dnf
      install_command: fd-find
      uninstall_command: fd-find
      official_support: true
      platform_requirements:
        - os: fedora
        - os: centos
        - os: rhel
    - install_method: pacman
      install_command: fd
      uninstall_command: fd
      official_support: true
      platform_requirements:
        - os: arch
        - os: manjaro
    - install_method: zypper
      install_command: fd
      uninstall_command: fd
      official_support: true
      platform_requirements:
        - os: opensuse
    - install_method: emerge
      install_command: sys-apps/fd
      uninstall_command: sys-apps/fd
      official_support: true
      platform_requirements:
        - os: gentoo
    - install_method: eopkg
      install_command: fd
      uninstall_command: fd
      official_support: true
      platform_requirements:
        - os: solus
    - install_method: xbps
      install_command: fd
      uninstall_command: fd
      official_support: true
      platform_requirements:
        - os: void
    - install_method: apk
      install_command: fd
      uninstall_command: fd
      official_support: true
      platform_requirements:
        - os: alpine
    - install_method: nixpkgs
      install_command: fd
      uninstall_command: fd
      official_support: true
      platform_requirements:
        - os: nixos
    - install_method: cargo
      install_command: fd-find
      uninstall_command: fd-find
      official_support: true
freebsd:
  install_method: pkg
  install_command: fd
  uninstall_command: fd
  official_support: true
openbsd:
  install_method: pkg_add
  install_command: fd
  uninstall_command: fd
  official_support: true
