name: fzf
description: A command-line fuzzy finder
category: Utilities
default: true
desktop_environments:
  - all
macos:
  install_method: brew
  install_command: fzf
  uninstall_command: fzf
  official_support: true
  post_install:
    - shell: $(brew --prefix)/opt/fzf/install --all
  alternatives:
    - install_method: macports
      install_command: fzf
      uninstall_command: fzf
      official_support: true
windows:
  install_method: winget
  install_command: junegunn.fzf
  uninstall_command: junegunn.fzf
  official_support: true
  alternatives:
    - install_method: chocolatey
      install_command: fzf
      uninstall_command: fzf
      official_support: true
    - install_method: scoop
      install_command: fzf
      uninstall_command: fzf
      official_support: true
linux:
  install_method: apt
  install_command: fzf
  uninstall_command: fzf
  official_support: true
  platform_requirements:
    - os: debian
    - os: ubuntu
  alternatives:
    - install_method: dnf
      install_command: fzf
      uninstall_command: fzf
      official_support: true
      platform_requirements:
        - os: fedora
        - os: centos
        - os: rhel
    - install_method: pacman
      install_command: fzf
      uninstall_command: fzf
      official_support: true
      platform_requirements:
        - os: arch
        - os: manjaro
    - install_method: zypper
      install_command: fzf
      uninstall_command: fzf
      official_support: true
      platform_requirements:
        - os: opensuse
    - install_method: emerge
      install_command: app-shells/fzf
      uninstall_command: app-shells/fzf
      official_support: true
      platform_requirements:
        - os: gentoo
    - install_method: eopkg
      install_command: fzf
      uninstall_command: fzf
      official_support: true
      platform_requirements:
        - os: solus
    - install_method: xbps
      install_command: fzf
      uninstall_command: fzf
      official_support: true
      platform_requirements:
        - os: void
    - install_method: apk
      install_command: fzf
      uninstall_command: fzf
      official_support: true
      platform_requirements:
        - os: alpine
    - install_method: nixpkgs
      install_command: fzf
      uninstall_command: fzf
      official_support: true
      platform_requirements:
        - os: nixos
    - install_method: snap
      install_command: fzf
      uninstall_command: fzf
      official_support: false
freebsd:
  install_method: pkg
  install_command: fzf
  uninstall_command: fzf
  official_support: true
openbsd:
  install_method: pkg_add
  install_command: fzf
  uninstall_command: fzf
  official_support: true
