name: tldr
description: Simplified and community-driven man pages
category: Utilities
default: true
desktop_environments:
  - all
macos:
  install_method: brew
  install_command: tldr
  uninstall_command: tldr
  official_support: true
  alternatives:
    - install_method: macports
      install_command: tldr
      uninstall_command: tldr
      official_support: true
windows:
  install_method: winget
  install_command: tldr-pages.tlrc
  uninstall_command: tldr-pages.tlrc
  official_support: true
  alternatives:
    - install_method: chocolatey
      install_command: tldr
      uninstall_command: tldr
      official_support: true
    - install_method: scoop
      install_command: tldr
      uninstall_command: tldr
      official_support: true
linux:
  install_method: apt
  install_command: tldr
  uninstall_command: tldr
  official_support: true
  platform_requirements:
    - os: debian
    - os: ubuntu
  alternatives:
    - install_method: dnf
      install_command: tldr
      uninstall_command: tldr
      official_support: true
      platform_requirements:
        - os: fedora
        - os: centos
        - os: rhel
    - install_method: pacman
      install_command: tldr
      uninstall_command: tldr
      official_support: true
      platform_requirements:
        - os: arch
        - os: manjaro
    - install_method: zypper
      install_command: tldr
      uninstall_command: tldr
      official_support: true
      platform_requirements:
        - os: opensuse
    - install_method: emerge
      install_command: app-doc/tldr
      uninstall_command: app-doc/tldr
      official_support: true
      platform_requirements:
        - os: gentoo
    - install_method: eopkg
      install_command: tldr
      uninstall_command: tldr
      official_support: true
      platform_requirements:
        - os: solus
    - install_method: xbps
      install_command: tldr
      uninstall_command: tldr
      official_support: true
      platform_requirements:
        - os: void
    - install_method: apk
      install_command: tldr
      uninstall_command: tldr
      official_support: true
      platform_requirements:
        - os: alpine
    - install_method: nixpkgs
      install_command: tldr
      uninstall_command: tldr
      official_support: true
      platform_requirements:
        - os: nixos
    - install_method: pip
      install_command: tldr
      uninstall_command: tldr
      official_support: true
    - install_method: npm
      install_command: tldr
      uninstall_command: tldr
      official_support: true
    - install_method: cargo
      install_command: tealdeer
      uninstall_command: tealdeer
      official_support: true
freebsd:
  install_method: pkg
  install_command: tldr
  uninstall_command: tldr
  official_support: true
openbsd:
  install_method: pkg_add
  install_command: tldr
  uninstall_command: tldr
  official_support: true
