version: 2
project_name: devex-plugin-package-manager-apt
# Set git tag pattern to match clean semver tags (v1.2.3)
git:
  tag_sort: -version:refname
builds:
  - id: plugin-package-manager-apt
    main: ./packages/package-manager-apt
    binary: devex-plugin-package-manager-apt
    dir: packages/package-manager-apt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"
      - "-X main.version={{.Version}}"
      - "-X main.commit={{.Commit}}"
      - "-X main.date={{.Date}}"
archives:
  - id: plugin-package-manager-apt-archive
    name_template: "devex-plugin-package-manager-apt_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - plugin-package-manager-apt
checksum:
  name_template: checksums.txt
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: New Features
      regexp: ^.*?feat(\([[:word:]]+\))??!?:.+$
      order: 0
    - title: Bug Fixes
      regexp: ^.*?fix(\([[:word:]]+\))??!?:.+$
      order: 1
    - title: Others
      order: 999
release:
  github:
    owner: jameswlane
    name: devex
  name_template: "devex-plugin-package-manager-apt v{{ .Version }}"
  mode: replace
  draft: false
  prerelease: auto
