version: 2
project_name: devex-plugin-tool-stackdetector
monorepo:
  tag_prefix: plugin-tool-stackdetector-
  dir: packages/tool-stackdetector
builds:
  - id: plugin-tool-stackdetector
    main: .
    binary: devex-plugin-tool-stackdetector
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"
      - "-X main.version={{.Version}}"
      - "-X main.commit={{.Commit}}"
      - "-X main.date={{.Date}}"
archives:
  - id: plugin-tool-stackdetector-archive
    name_template: "devex-plugin-tool-stackdetector_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: checksums.txt
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: New Features
      regexp: ^.*?feat(\([[:word:]]+\))??!?:.+$
      order: 0
    - title: Bug Fixes
      regexp: ^.*?fix(\([[:word:]]+\))??!?:.+$
      order: 1
    - title: Others
      order: 999
release:
  github:
    owner: jameswlane
    name: devex
  name_template: "devex-plugin-tool-stackdetector v{{ .Version }}"
  mode: replace
  draft: false
  prerelease: auto
