apps:
  - name: Build Tools
    description: "Essential tools for building software"
    category: "Development"
    install_method: "apt"
    install_command: "build-essential pkg-config autoconf bison"
    uninstall_command: "build-essential pkg-config autoconf bison"
    dependencies:
      - "apt"

  - name: Rust and Cargo
    description: "Rust programming language and package manager Cargo"
    category: "Programming Languages"
    install_method: "apt"
    install_command: "rustc cargo"
    uninstall_command: "rustc cargo"
    dependencies:
      - "apt"

  - name: Clang
    description: "C/C++ compiler"
    category: "Development"
    install_method: "apt"
    install_command: "clang"
    uninstall_command: "clang"
    dependencies:
      - "apt"

  - name: Ruby Development Libraries
    description: "Libraries required for building Ruby software"
    category: "Development"
    install_method: "apt"
    install_command: "libssl-dev libreadline-dev zlib1g-dev libyaml-dev libncurses5-dev libffi-dev libgdbm-dev"
    uninstall_command: "libssl-dev libreadline-dev zlib1g-dev libyaml-dev libncurses5-dev libffi-dev libgdbm-dev"
    dependencies:
      - "apt"

  - name: Image Processing Tools
    description: "Tools for processing images"
    category: "Image Processing"
    install_method: "apt"
    install_command: "libvips imagemagick libmagickwand-dev mupdf mupdf-tools"
    uninstall_command: "libvips imagemagick libmagickwand-dev mupdf mupdf-tools"
    dependencies:
      - "apt"

  - name: Redis Tools
    description: "Tools for working with Redis"
    category: "Databases"
    install_method: "apt"
    install_command: "redis-tools"
    uninstall_command: "redis-tools"
    dependencies:
      - "redis"
      - "apt"

  - name: SQLite Libraries
    description: "SQLite libraries for database operations"
    category: "Databases"
    install_method: "apt"
    install_command: "sqlite3 libsqlite3-0"
    uninstall_command: "sqlite3 libsqlite3-0"
    dependencies:
      - "apt"

  - name: MySQL Development Libraries
    description: "Development libraries for MySQL"
    category: "Databases"
    install_method: "apt"
    install_command: "default-libmysqlclient-dev"
    uninstall_command: "default-libmysqlclient-dev"
    dependencies:
      - "apt"

  - name: pre-commit
    description: "A framework for managing and maintaining multi-language pre-commit hooks"
    category: "Development Tools"
    install_method: "apt"
    install_command: "pre-commit"
    uninstall_command: "pre-commit"
    dependencies:
      - "apt"

  - name: VLC
    description: "A free and open-source multimedia player"
    category: "Multimedia"
    install_method: "apt"
    install_command: "vlc"
    uninstall_command: "vlc"
    dependencies:
      - "apt"

  - name: Flameshot
    description: "A powerful, simple, and open-source screenshot tool"
    category: "System Utilities"
    install_method: "apt"
    install_command: "flameshot"
    uninstall_command: "flameshot"
    dependencies:
      - "apt"

  - name: "Proton Mail"
    description: "Secure email app by Proton"
    category: "Optional Apps"
    install_method: "deb"
    install_command: "wget https://proton.me/download/mail/linux/1.2.4/ProtonMail-desktop-beta.deb && sudo apt install ./ProtonMail-desktop-beta.deb"
    uninstall_command: "sudo apt remove protonmail-desktop-beta"
    dependencies:
      - "apt"

  - name: "Proton VPN"
    description: "VPN service by Proton"
    category: "Optional Apps"
    install_method: "script"
    install_command: |
      wget https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.4_all.deb &&
      sudo dpkg -i ./protonvpn-stable-release_1.0.4_all.deb && sudo apt update &&
      sudo apt install proton-vpn-gnome-desktop libayatana-appindicator3-1 gir1.2-ayatanaappindicator3-0.1 gnome-shell-extension-appindicator
    uninstall_command: "sudo apt remove proton-vpn-gnome-desktop libayatana-appindicator3-1 gir1.2-ayatanaappindicator3-0.1 gnome-shell-extension-appindicator"
    dependencies:
      - "apt"

  - name: "Proton Pass"
    description: "Password manager by Proton"
    category: "Optional Apps"
    install_method: "deb"
    install_command: "wget https://proton.me/download/pass/linux/proton-pass_1.23.1_amd64.deb && sudo apt install ./proton-pass_1.23.1_amd64.deb"
    uninstall_command: "sudo apt remove proton-pass"
    dependencies:
      - "apt"

  - name: "Zen Browser"
    description: "A secure and private browser"
    category: "Optional Apps"
    install_method: "flatpak"
    install_command: "flatpak install flathub io.github.zen_browser.zen"
    uninstall_command: "flatpak remove io.github.zen_browser.zen"
    dependencies:
      - "flatpak"

  - name: Fastfetch
    description: "A fast and lightweight system information tool"
    category: "System Utilities"
    install_method: "deb"
    install_command: "fastfetch-linux-amd64.deb"
    download_url: "https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-amd64.deb"
    cleanup_files:
      - "/tmp/fastfetch-linux-amd64.deb"

  - name: GitHub CLI
    description: "A command-line tool for GitHub"
    category: "Development Tools"
    install_method: "apt"
    install_command: "gh"
    uninstall_command: "gh"
    dependencies:
      - "curl"
      - "apt"
    apt_sources:
      - source: "/usr/share/keyrings/githubcli-archive-keyring.gpg"
        list_file: "/etc/apt/sources.list.d/github-cli.list"
        repo: "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    gpg_url: "https://cli.github.com/packages/githubcli-archive-keyring.gpg"

  - name: Gnome Tweaks
    description: "A tool to customize advanced GNOME settings"
    category: "System Utilities"
    install_method: "apt"
    install_command: "gnome-tweaks"
    uninstall_command: "gnome-tweaks"
    dependencies:
      - "apt"

  - name: Lazy Docker
    description: "A simple terminal UI for Docker and Docker Compose"
    category: "System Utilities"
    install_method: "manual"
    install_command: "lazydocker"
    download_url: "https://github.com/jesseduffield/lazydocker/releases/latest/download/lazydocker_${LAZYDOCKER_VERSION}_Linux_x86_64.tar.gz"
    install_dir: "/usr/local/bin"
    cleanup_files:
      - "/tmp/lazydocker.tar.gz"
      - "/tmp/lazydocker"

  - name: Lazy Git
    description: "A simple terminal UI for Git commands"
    category: "Development Tools"
    install_method: "manual"
    install_command: "lazygit"
    download_url: "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
    install_dir: "/usr/local/bin"
    cleanup_files:
      - "/tmp/lazygit.tar.gz"
      - "/tmp/lazygit"

  - name: LocalSend
    description: "A tool for sending files over local networks"
    category: "Networking"
    install_method: "deb"
    install_command: "localsend.deb"
    download_url: "https://github.com/localsend/localsend/releases/latest/download/LocalSend-${LOCALSEND_VERSION}-linux-x86-64.deb"
    cleanup_files:
      - "/tmp/localsend.deb"

  - name: Mise
    description: "A tool for managing multiple versions of programming languages"
    category: "Language Management"
    install_method: "apt"
    install_command: "mise"
    uninstall_command: "mise"
    dependencies:
      - "gpg"
      - "wget"
      - "curl"
      - "apt"
    apt_sources:
      - source: "/etc/apt/keyrings/mise-archive-keyring.gpg"
        list_file: "/etc/apt/sources.list.d/mise.list"
        repo: "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main"
    gpg_url: "https://mise.jdx.dev/gpg-key.pub"

  - name: Nala
    description: "A front-end for the apt package manager with better output"
    category: "Package Management"
    install_method: "apt"
    install_command: "nala"
    uninstall_command: "nala"
    dependencies:
      - "apt"

  - name: Neovim
    description: "A highly extensible and customizable text editor"
    category: "Development Tools"
    install_method: "manual"
    install_command: "nvim"
    download_url: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
    install_dir: "/usr/local/bin"
    cleanup_files:
      - "/tmp/nvim-linux64"
      - "/tmp/nvim.tar.gz"
    post_install:
      - command: "[ ! -d \"$HOME/.config/nvim\" ] && git clone https://github.com/LazyVim/starter ~/.config/nvim"
      - command: "sed -i 's/checker = { enabled = true }/checker = { enabled = true, notify = false }/g' ~/.config/nvim/lua/config/lazy.lua"
      - command: "mkdir -p ~/.config/nvim/plugin/after"
      - command: "cp ~/.local/share/devex/configs/neovim/transparency.lua ~/.config/nvim/plugin/after/"
      - command: "cp ~/.local/share/devex/themes/neovim/tokyo-night.lua ~/.config/nvim/lua/plugins/theme.lua"
      - command: "cp ~/.local/share/devex/configs/neovim/lazyvim.json ~/.config/nvim/lazyvim.json"

  - name: Typora
    description: "A minimal and configurable markdown editor"
    category: "Text Editors"
    install_method: "apt"
    install_command: "typora"
    uninstall_command: "typora"
    dependencies:
      - "wget"
      - "apt"
    apt_sources:
      - source: "/etc/apt/trusted.gpg.d/typora.asc"
        repo: "deb https://typora.io/linux ./"
    gpg_url: "https://typora.io/linux/public-key.asc"
    post_install:
      - command: "mkdir -p ~/.config/Typora/themes"
      - command: "cp ~/.local/share/devex/themes/typora/ia_typora.css ~/.config/Typora/themes/"
      - command: "cp ~/.local/share/devex/themes/typora/ia_typora_night.css ~/.config/Typora/themes/"

  - name: Docker
    description: "A platform for developing, shipping, and running containerized applications"
    category: "Container Management"
    install_method: "apt"
    install_command: "docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras"
    uninstall_command: "docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras"
    dependencies:
      - "wget"
      - "apt"
    apt_sources:
      - source: "/etc/apt/keyrings/docker.asc"
        repo: "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable"
    gpg_url: "https://download.docker.com/linux/debian/gpg"
    post_install:
      - command: "sudo usermod -aG docker ${USER}"
      - command: "echo '{\"log-driver\":\"local\",\"log-opts\":{\"max-size\":\"10m\",\"max-file\":\"5\"}}' | sudo tee /etc/docker/daemon.json > /dev/null"

  - name: Eza
    description: "A modern replacement for the ls command"
    category: "System Utilities"
    install_method: "apt"
    install_command: "eza"
    uninstall_command: "eza"
    dependencies:
      - "gpg"
      - "wget"
      - "apt"
    apt_sources:
      - source: "/etc/apt/keyrings/gierens.gpg"
        repo: "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main"
    gpg_url: "https://raw.githubusercontent.com/eza-community/eza/main/deb.asc"
    post_install:
      - command: "sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list"

  - name: Firefox Developer Edition
    description: "A version of Firefox tailored for developers"
    category: "Web Browsers"
    install_method: "manual"
    install_command: "firefox-dev"
    download_url: "https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US"
    install_dir: "~/.local/opt"
    symlink: "~/.local/bin/firefox-dev"
    post_install:
      - command: "ln -s ~/.local/opt/firefox/firefox ~/.local/bin/firefox-dev"
      - command: "PATH=${PATH}:${HOME}/.local/bin"

  - name: Flatpak
    description: "A system for building and distributing desktop applications on Linux"
    category: "Package Management"
    install_method: "apt"
    install_command: "flatpak gnome-software-plugin-flatpak"
    uninstall_command: "flatpak gnome-software-plugin-flatpak"
    dependencies:
      - "apt"
    post_install:
      - command: "sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo"

  - name: fzf
    description: "A command-line fuzzy finder"
    category: "Utilities"
    install_method: "apt"
    install_command: "fzf"
    uninstall_command: "fzf"
    dependencies:
      - "apt"

  - name: ripgrep
    description: "A line-oriented search tool that recursively searches your current directory"
    category: "Utilities"
    install_method: "apt"
    install_command: "ripgrep"
    uninstall_command: "ripgrep"
    dependencies:
      - "apt"

  - name: bat
    description: "A cat clone with syntax highlighting and Git integration"
    category: "Utilities"
    install_method: "apt"
    install_command: "bat"
    uninstall_command: "bat"
    dependencies:
      - "apt"

  - name: zoxide
    description: "A smarter cd command for terminal navigation"
    category: "Utilities"
    install_method: "apt"
    install_command: "zoxide"
    uninstall_command: "zoxide"
    dependencies:
      - "apt"

  - name: plocate
    description: "A faster and smaller locate command replacement"
    category: "Utilities"
    install_method: "apt"
    install_command: "plocate"
    uninstall_command: "plocate"
    dependencies:
      - "apt"

  - name: btop
    description: "A resource monitor that shows usage and stats for processors, memory, disks, network, and processes"
    category: "System Monitoring"
    install_method: "apt"
    install_command: "btop"
    uninstall_command: "btop"
    dependencies:
      - "apt"

  - name: apache2-utils
    description: "A collection of utilities including tools to create HTTP authentication files"
    category: "Utilities"
    install_method: "apt"
    install_command: "apache2-utils"
    uninstall_command: "apache2-utils"
    dependencies:
      - "apt"

  - name: fd-find
    description: "A simple, fast, and user-friendly alternative to find"
    category: "Utilities"
    install_method: "apt"
    install_command: "fd-find"
    uninstall_command: "fd-find"
    dependencies:
      - "apt"


  - name: Bun
    description: "A fast all-in-one JavaScript runtime"
    category: "Programming Languages"
    install_method: "mise"
    install_command: "bun@latest"
    uninstall_command: "bun"
    dependencies:
      - "mise"

  - name: Deno
    description: "A modern runtime for JavaScript and TypeScript"
    category: "Programming Languages"
    install_method: "mise"
    install_command: "deno@latest"
    uninstall_command: "deno"
    dependencies:
      - "mise"

  - name: Erlang
    description: "A programming language used to build massively scalable soft real-time systems"
    category: "Programming Languages"
    install_method: "mise"
    install_command: "erlang@latest"
    uninstall_command: "erlang"
    dependencies:
      - "mise"
    post_install:
      - command: "mise use --global elixir@latest"
      - command: "mise x elixir -- mix local.hex --force"

  - name: Go
    description: "Go programming language"
    category: "Programming Languages"
    install_method: "mise"
    install_command: "go@latest"
    uninstall_command: "go"
    dependencies:
      - "mise"
    post_install:
      - command: "code --install-extension golang.go"

  - name: Java
    description: "Java programming language"
    category: "Programming Languages"
    install_method: "mise"
    install_command: "java@latest"
    uninstall_command: "java"
    dependencies:
      - "mise"

  - name: Node.js
    description: "Node.js runtime"
    category: "Programming Languages"
    install_method: "mise"
    install_command: "node@lts"
    uninstall_command: "node"
    dependencies:
      - "mise"

  - name: Python
    description: "Python programming language"
    category: "Programming Languages"
    install_method: "mise"
    install_command: "python@latest"
    uninstall_command: "python"
    dependencies:
      - "mise"

  - name: Ruby
    description: "Ruby programming language"
    category: "Programming Languages"
    install_method: "mise"
    install_command: "ruby@latest"
    uninstall_command: "ruby"
    dependencies:
      - "mise"
    post_install:
      - command: "mise x ruby -- gem install rails --no-document"

  - name: Rails
    description: "Rails web application framework"
    category: "Web Frameworks"
    install_method: "mise"
    install_command: "rails"
    uninstall_command: "rails"
    dependencies:
      - "ruby"

  - name: MySQL
    description: "MySQL relational database management system"
    category: "Databases"
    install_method: "docker"
    install_command: "mysql:8.4"
    docker_options:
      ports:
        - "127.0.0.1:3306:3306"
      container_name: "mysql8"
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
      restart_policy: "unless-stopped"

  - name: Redis
    description: "Redis in-memory data structure store"
    category: "Databases"
    install_method: "docker"
    install_command: "redis:7"
    docker_options:
      ports:
        - "127.0.0.1:6379:6379"
      container_name: "redis"
      restart_policy: "unless-stopped"

  - name: PostgreSQL
    description: "PostgreSQL relational database system"
    category: "Databases"
    install_method: "docker"
    install_command: "postgres:16"
    docker_options:
      ports:
        - "127.0.0.1:5432:5432"
      container_name: "postgres16"
      environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
      restart_policy: "unless-stopped"

  - name: Podman
    description: "A daemonless container engine for developing, managing, and running OCI Containers"
    category: "Container Management"
    install_method: "apt"
    install_command: "podman"
    uninstall_command: "podman"
    dependencies:
      - "apt"

  - name: JetBrains Toolbox
    description: "A tool to manage your JetBrains IDEs and other products"
    category: "Development Tools"
    install_method: "appimage"
    install_command: "jetbrains-toolbox"
    uninstall_command: ""  # Manual uninstall for AppImages
    dependencies:
      - "libfuse2"
    appimage_install:
      download_url: "https://download.jetbrains.com/toolbox/jetbrains-toolbox-2.3.2.31487.tar.gz"
      install_dir: "$HOME/Applications"
      binary: "jetbrains-toolbox"

  - name: Ulauncher
    description: "A fast application launcher for Linux"
    category: "Utility"
    install_method: "apt"
    install_command: "ulauncher"
    uninstall_command: "ulauncher"
    config_files:
      - source: "~/.local/share/devex/configs/ulauncher.desktop"
        destination: "~/.config/autostart/ulauncher.desktop"
      - source: "~/.local/share/devex/configs/ulauncher.json"
        destination: "~/.config/ulauncher/settings.json"
    gpg_url: "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xfaf1020699503176"
    apt_sources:
      - source: "/usr/share/keyrings/ulauncher-archive-keyring.gpg"
        list_file: "/etc/apt/sources.list.d/ulauncher-jammy.list"
        repo: "deb [signed-by=/usr/share/keyrings/ulauncher-archive-keyring.gpg] http://ppa.launchpad.net/agornostal/ulauncher/ubuntu jammy main"
    dependencies:
      - "gnupg"
      - "apt"
    post_install:
      - command: "gtk-launch ulauncher.desktop"
      - sleep: 2  # Ensure time for Ulauncher to set defaults
