# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# GoReleaser template for DevEx plugins
# Copy this to your plugin directory and customize:
# 1. Replace PLUGIN_NAME with your plugin name (e.g., desktop-gnome)
# 2. Update project_name, tag_prefix, and dir
# 3. Adjust build settings as needed
version: 2
project_name: devex-plugin-PLUGIN_NAME
monorepo:
  tag_prefix: packages/PLUGIN_NAME/v
  dir: packages/PLUGIN_NAME
before:
  hooks:
    - go mod tidy
    - go test ./...
builds:
  - id: plugin-PLUGIN_NAME
    main: .
    binary: devex-plugin-PLUGIN_NAME
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"
      - "-X main.version={{.Version}}"
      - "-X main.commit={{.Commit}}"
      - "-X main.date={{.Date}}"
archives:
  - id: plugin-PLUGIN_NAME-archive
    name_template: "devex-plugin-PLUGIN_NAME_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
checksum:
  name_template: checksums.txt
  algorithm: sha256
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: 🚀 Features
      regexp: ^.*?feat(\([[:word:]]+\))??!?:.+$
      order: 0
    - title: 🐛 Bug Fixes
      regexp: ^.*?fix(\([[:word:]]+\))??!?:.+$
      order: 1
    - title: Others
      order: 999
release:
  github:
    owner: jameswlane
    name: devex
  name_template: "Plugin PLUGIN_NAME v{{ .Version }}"
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## DevEx Plugin: PLUGIN_NAME {{ .Version }}

    ### Installation
    ```bash
    devex plugin install PLUGIN_NAME
    ```
  footer: |
    **Full Changelog**: https://github.com/jameswlane/devex/compare/{{ .PreviousTag }}...{{ .Tag }}
