programming_languages:
  - name: Bun
    description: 'A fast all-in-one JavaScript runtime'
    category: 'Programming Languages'
    install_method: 'mise'
    install_command: 'bun@latest'
    uninstall_command: 'bun'
    default: false
    dependencies:
      - 'mise'
  - name: Deno
    description: 'A modern runtime for JavaScript and TypeScript'
    category: 'Programming Languages'
    install_method: 'mise'
    install_command: 'deno@latest'
    uninstall_command: 'deno'
    default: false
    dependencies:
      - 'mise'
  - name: Elixir
    description: ''
    category: 'Programming Languages'
    install_method: 'mise'
    install_command: 'elixir@latest'
    uninstall_command: 'elixir'
    default: false
    dependencies:
      - 'mise'
      - 'erlang'
  - name: Erlang
    description: 'A programming language used to build massively scalable soft real-time systems'
    category: 'Programming Languages'
    install_method: 'mise'
    install_command: 'erlang@latest'
    uninstall_command: 'erlang'
    default: false
    dependencies:
      - 'mise'
  - name: Go
    description: 'Go programming language'
    category: 'Programming Languages'
    install_method: 'mise'
    install_command: 'go@latest'
    uninstall_command: 'go'
    default: true
    dependencies:
      - 'mise'
  - name: Java
    description: 'Java programming language'
    category: 'Programming Languages'
    install_method: 'mise'
    install_command: 'java@latest'
    uninstall_command: 'java'
    default: false
    dependencies:
      - 'mise'
  - name: Node.js
    description: 'Node.js runtime'
    category: 'Programming Languages'
    install_method: 'mise'
    install_command: 'node@lts'
    uninstall_command: 'node'
    default: true
    dependencies:
      - 'mise'
  - name: Python
    description: 'Python programming language'
    category: 'Programming Languages'
    install_method: 'mise'
    install_command: 'python@latest'
    uninstall_command: 'python'
    default: true
    dependencies:
      - 'mise'
  - name: Ruby
    description: 'Ruby programming language'
    category: 'Programming Languages'
    install_method: 'mise'
    install_command: 'ruby@latest'
    uninstall_command: 'ruby'
    default: true
    dependencies:
      - 'mise'
  - name: Rust
    description: 'Rust programming language'
    category: 'Programming Languages'
    install_method: 'mise'
    install_command: 'rust@latest'
    uninstall_command: 'rust'
    default: false
    dependencies:
      - 'mise'
  - name: Swift
    description: ''
    category: 'Programming Languages'
    install_method: 'mise'
    install_command: 'swift@latest'
    uninstall_command: 'swift'
    default: false
    dependencies:
      - 'mise'
  - name: Zig
    description: ''
    category: 'Programming Languages'
    install_method: 'mise'
    install_command: 'zig@latest'
    uninstall_command: 'zig'
    default: false
    dependencies:
      - 'mise'
fonts:
  - name: 'Cascadia Mono'
    method: 'url'
    url: 'https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaMono.zip'
    destination: '~/.local/share/fonts'
  - name: 'iA Writer Mono'
    method: 'url'
    url: 'https://github.com/iaolo/iA-Fonts/archive/refs/heads/master.zip'
    extract_path: 'iA-Fonts-master/iA Writer Mono/Static'
    destination: '~/.local/share/fonts'
  - name: 'Meslo LG S'
    method: 'oh-my-posh'
  - name: 'Fira Code'
    method: 'homebrew'
shell: []
