# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: devex-plugin-package-manager-yay
monorepo:
  tag_prefix: packages/package-manager-yay/v
  dir: packages/package-manager-yay
builds:
  - id: plugin-package-manager-yay
    main: .
    binary: devex-plugin-package-manager-yay
    dir: packages/package-manager-yay
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"
      - "-X main.version={{.Version}}"
      - "-X main.commit={{.Commit}}"
      - "-X main.date={{.Date}}"
archives:
  - id: plugin-package-manager-yay-archive
    name_template: "devex-plugin-package-manager-yay_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: checksums.txt
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: New Features
      regexp: ^.*?feat(\([[:word:]]+\))??!?:.+$
      order: 0
    - title: Bug Fixes
      regexp: ^.*?fix(\([[:word:]]+\))??!?:.+$
      order: 1
    - title: Others
      order: 999
release:
  github:
    owner: jameswlane
    name: devex
  name_template: "devex-plugin-package-manager-yay v{{ .Version }}"
  mode: replace
  draft: false
  prerelease: auto
