name: CI

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Go modules
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - name: Build
        run: go build -o ./bin/devex -v ./cmd/devex

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.1

      - name: Test
        run: go test ./...