name: Docs
on:
    push:
        branches:
            - main
permissions:
    contents: write
env:
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
    deploy:
        runs-on: ubuntu-latest
        if: github.event.repository.fork == false
        steps:
            - name: Checkout source
              uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - name: Install Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'
            - name: Setup Cache
              uses: actions/cache@v4
              with:
                  key: mkdocs-material-${{ env.cache_id }}
                  path: .cache
                  restore-keys: |
                      mkdocs-material-
            - name: Install dependencies
              run: pip install --no-deps -r requirements.txt
            - name: Build site
              run: mkdocs gh-deploy --force --remote-name origin --remote-branch gh-pages --token ${{ secrets.GH_TOKEN }}
