name: Issue Closed
on:
  issues:
    types: [closed]
jobs:
  issue-closed:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = await github.paginate(
              github.rest.issues.listLabelsOnIssue, {
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
              }
            )
            if (labels.find(label => label.name === 'state: needs triage')) {
              github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'state: needs triage'
              })
            }
